--- # Twitter API Credentials
Twitter_API:
    CONSUMER_KEY: 'V1XCyXScnXDZh232FAIvjSd2e'
    CONSUMER_SECRET: 'JOB36LqZhd8A6WJ4zmd7ZBy3As2CQhK9uLXonlpaliFJYMhcSv'
    AUTH_TOKEN: '43233942-pMGIuekO53ZywjjOe3JVZJoekOLWN5KzIfj1NcvKP'
    AUTH_SECRET: 'ibXRDGgO4g9WA8buMFvzfyJebA6JkhCN26WMUeGeA'

